# Generated by Django 3.2.20 on 2023-09-02 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_remove_track_track_ref'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='genre',
            new_name='genre_id',
        ),
    ]
